### ISSUE TITLE
What do you like to DIY?

### ISSUE THREAD

**Issue by silvenon** [benmvp/ama#1]
(Reading your GitHub bio.)

**Comment by benmvp** [comment]
My wife and I love to watch HGTV ([Fixer Upper](http://www.hgtv.com/shows/fixer-upper), [Flip or Flop](http://www.hgtv.com/shows/flip-or-flop), etc.) so a lot of my DIY projects are around the house. Lately I've really gotten into building things.

When I was on paternity leave in September, I extended our garden by building a handful of planter boxes for trees, veggies and herbs. I built the boxes out of 10-year old fence wood that someone was giving away on Craigslist. Earlier in the year my wife and I sanded and power washed that wood to make a wood accent wall in our dining room.

I _really_ wanna redo our kitchen one day, but I'll need to watch some more TV so I can know what I'm doing. 😉 

Do you DIY?

**Comment by silvenon** [comment]
Cool, sounds like you're pretty good at building and repairing things! It's amazing what TV/YouTube can teach us these days…

> Do you DIY?

Nah, I'm terrible, I'd call a repairman/mechanic/etc. for every small problem I have. 😅
