### ISSUE TITLE
ES6 Param Destructuring

### ISSUE THREAD

**Issue by jsonberry** [benmvp/ama#10]
Hey Ben, thanks for your talk at Chain React!

# RE: Nested object destructuring in function parameters
## The Setup
Given:
```javascript
function foo ({ bar: { baz: { fee: fi } } }) {
    console.log(fi) // 'Hello World'
}
```

Let's say `foo` gets used like this:

`foo(externalApiEndpoint)`

If that external API fails to return something we expect in that chain of destructuring, let's say `baz` comes back as `undefined`, then `console.log(fi)` will error.

OK, so default params to the rescue, right?
```javascript
function foo ({ bar: { baz: { fee: fi = 'Hello World' } } }) {
    console.log(fi) // 'Hello World'
}
```

Nope, because `baz` was undefined. 

Generally, I have stayed away from these sort of destructuring patterns *if* I have to check for data/object paths.

## Question
 Have you come across any succinct patterns for data checking + param object destructuring? Maybe a barometer for when _not_ to use destructuring in function params?

**Comment by benmvp** [comment]
Hey Jason! Glad you enjoyed the talk!

So what you've pointed out is precisely why I don't use nested destructuring much. If you want to be 100% safe, you need to default everything, `bar`, `baz` & `fe`.

I forgot to mention this in the talk, but if you find yourself doing nested destructuring, particularly in the function header, I feel that the function itself has a broken API. The function _really_ shouldn't be expected such a deeply nested structure passed to it.

But in your hypothetical example, the data is coming directly from the API so you don't have much control over its shape. I, like you, avoid these sort of destructuring patterns when they are that nested. I think there are diminishing returns. The pattern is a little easier on the eyes when it's not in the header and you can use line breaks, but still.

So to answer your question, I pretty much only go one layer deep and only in the function body. That help any?

**Comment by jsonberry** [comment]
Oh yes it does, mostly because it's good to see other people confirm the same stuff I have run into.

> if you find yourself doing nested destructuring, particularly in the function header, I feel that the function itself has a broken API

😆 Mmmhmm
Yes, and that is exactly the sort of case I was dealing with!

In a large long-running project for a client we were responsible for front-end design efforts, the client contracted a separate party for building out the API. During development, there were about four different API environments that were in play that would not carry consistent results and we had no control over what would get returned, thus many pieces of our transform layers had to include latches.

Eventually, we wrote out this helper utility to help keep our code succinct and not have to context switch so much:
```javascript
function hasEmptyProps(data) {
    if (!_.isPlainObject(data) || _.isEmpty(data)) {
        return true
    }

    return _.chain(data)
        .map()
        .filter(_.isEmpty)
        .reject(_.isNumber)
        .value()
        .length > 0
}
```

And it's implementation would look something like this:

```javascript
function transformData(data) {
    if (hasEmptyProps(data)) {
        return false // There was some listener / observer like behavior written so the function would get called again if it was unable to continue because of bad data
    }

    const { stuff } = data
    ...etc
}
```

**Comment by jsonberry** [comment]
By the way, that bit about why spreading into an array works and how it touches upon immutability was a good bit to talk about 👌 

Depending on the environment, sometimes I couple lodash with spreading/resting to retain immutability, like so:

```javascript
function handleTransaction(...params) {
    const [ order = {}, lines = {}, creditCard = {} ] = _.cloneDeep(params)
    etc..
}
```

☝️ That hasn't really caught on with my coworkers, so I use it when I can :man_shrugging: 

Thanks for the response! 👋

**Comment by benmvp** [comment]
I can kinda see why it hasn't caught on. 😉 . You are obfuscating the function's interface by taking away `order`, `lines` & `creditCard` from the function header. Why do you need to clone them when you're handling transaction? You're still going to add data to them?

**Comment by jsonberry** [comment]
@benmvp ah, yes it would get used in a transformative layer, sorry that was a bad example.

When dealing with a facet-like / pointer layer I needed to often pass data into a transformative layer to prep the data for the UI (no control over the structure coming back from the API). Using lodash's cloneDeep became a good practice.

Here's a contrived example. Instead of something like this:
```javascript
function transformPaymentFacetData(paymentObj, dateObj) {
    if (!paymentObj || !dateObj) {
        return
    }

    const payment = _.cloneDeep(paymentObj);
    const date = _.cloneDeep(dateObj);

   return {
        payment: `Your payment of ${paymentPrepForUI(payment.amount)}`,
        date: `Has been received on ${datePrepForUI(date.dayOfWeek)}`
   }
}
```

I attempted to clone all params and do assignment at once, with destructuring, resting, and default params. 
```javascript
function transformPaymentFacetData(...params) {
    const [ payment = {}, date = {} ] = _.cloneDeep(params)
    ...
}

```

This sort of pattern only worked well in a layer where specific pieces were getting passed into a transform step that would prep the data for display to a UI component. You're right that it's confusing though, which goes to show that these patterns should get used if they adding value.

**Comment by benmvp** [comment]
Ah, yeah that's a clearer example.

So my question then is why do you have to deep clone if you're just ultimately displaying it to the UI. You should only need to clone if you're planning on mutating the data such as adding to the `paymentObj`. If not, it seems like you're doing extra work for nothing.

**Comment by jsonberry** [comment]
> You should only need to clone if you're planning on mutating the data such as adding to the paymentObj

Yes, in this particular application, those situations were plentiful.

I think the necessity of cloning came down to:
- Implementation of state management (Baobob + bespoke Observer-like behavior, it was written before Redux was released and unique to the project)
- *The requirement of the same data needing to be used in disparate locations throughout the application, and frequently requiring additions/mutations 
- *The fragmentation of the API structure and the necessity to string together different pieces to fit UI requirements

*These, I'm sure, were the main reasons.

Some of these issues arose because of iterative designs, I think during active development there were four new designs shipped, coupled with no control over the API... it was a fun project 😄
