### ISSUE TITLE
render code on web page

### ISSUE THREAD

**Issue by Sylvenas** [benmvp/ama#11]
Hi,@benmvp,I want to know how to render such a beautiful code on the web page, are you using any great CSS frameworks?
![image](https://user-images.githubusercontent.com/10754058/29454101-875b6c5a-843e-11e7-86d9-ddc6e24f16cc.png)

thanks a lot !

**Comment by benmvp** [comment]
Thanks!

I use Github pages with Jekyll for my site. See this post from Github: https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

I write all my posts in Markdown, which Github converts into HTML with [`kramdown`](http://kramdown.gettalong.org/). The syntax highlighter is [`Rouge`](https://github.com/jneen/rouge). Then I use Solarized Light CSS color scheme from: http://ethanschoonover.com/solarized.

Hope that helps!
