### ISSUE TITLE
React Workshop - Mark read/unread

### ISSUE THREAD

**Issue by akster** [benmvp/ama#13]
https://github.com/akster/react-workshop/tree/master/09-mark-unread

Possible bug?

Steps to reproduce:
Select the first email.
Mark it as unread.
In email list view, "Mark read" button appears.  Mark it as read.
Mark the same issue as unread _again_.
In email list view, button does **not** appear.

**Comment by akster** [comment]
User error.

**Comment by benmvp** [comment]
👍
