### ISSUE TITLE
Fullstack APP - Geolocalization Web + MOBILE APP

### ISSUE THREAD

**Issue by cglsoft** [benmvp/ama#14]
Hi,  I am from Brazil, and a want to start to developer fullstack  app. So I need to know, how to start to developer?

My habilities. NODE + JS ES6 + HTML5 + CSS + EXPRESS + BOOTSTRAP

Thank you.

**Comment by benmvp** [comment]
Hi Claudio!

I appreciate your question, but I'm not quite sure how to help. You already know a great set of technologies. What sort of advice are you looking for?

**Comment by cglsoft** [comment]
So,

maybe you can help me with skeleton design. (Simple!!)
