### ISSUE TITLE
React App container and presentational component folder structuring

### ISSUE THREAD

**Issue by raymundoxmartinez** [benmvp/ama#18]
I am currently in the process of structuring a react web app and would like your opinion on the structuring of component folders/files.

current structure:

```
src
    -components(<-- these are the presentational components)
        -Admin
             -AdminNavbar.js
        -StoreOwners
             -StoreOwnerNavbar.js
        -Customers
    
    -containers
        -Admin
            -Admin_DashBoard.js
            -Admin_ProfilePage.js
        -StoreOwners
            -StoreOwner_DashBoard.js
            -StoreOwner_ProfilePage.js
        -Customers
```

I am wondering whether to separate the ProfilePage and Dashboard container components by having a different component entirely for the user based on their role(admin, storeowner, customer) like seen above. Or would it be better to have just one Dashboard, and Profile container that renders different features within them based on the role of the user that is logged in?

I would appreciate your thoughts on this. 

Thank you!

**Comment by benmvp** [comment]
Hey @raymundoxmartinez! So it really depends on what the components will look like. If the Admin and store owner dashboards are gonna be totally different, there's no real reason to have a single Dashboard that'll have a big if statement rendering two different components. So in that case having the two separate components makes sense.

But I suspect there'll be _some_ commonalities between the roles. So you may want to have separate admin and storeowner dashboard components but they both compose/use a shared dashboard component that has the commonalities.

**Comment by raymundoxmartinez** [comment]
Both dashboards will be close to identical, except for maybe 1 or 2 added features. So would you recommend i still divide them into different components(admin dashboard, and storeowner dashboard)? if so, why?  
I am wondering if i keep building different components based on the role, i would be creating two applications (i.e i would be building double the components). is there any performance benefits from rendering a component through a different route(/admin/dashboard, and storeowner/dashboard) over rendering features through conditional statements within the same route(/dashboard)?
