### ISSUE TITLE
emotionjs object importing

### ISSUE THREAD

**Issue by sht5** [benmvp/ama#21]
for each component i'm creating a "style" javascript file which exposes styled components for the original component so that i have semantic tags. for now i export each styled component individually and import all of them as such":
```
// new_live_pie.js
`import {
    PieContainer,
    Aligner
} from './new_live_pie.styles';`

```

```
// new_live_pie.styles.js
`export const Aligner = styled('div')`
    display: inline-block;
    flex: 1 0 15%;
    ${mq({
    marginBottom: [0,26]
})}`;



export const PieContainer = styled('div')`
    margin-left: auto;
    margin-right: auto;
    ${mq({
    width: [46,63],
    height: [46,63],
})}
`;`

```

regarding my need to import every styled component individually, is this a good practice? have a better one?

**Comment by benmvp** [comment]
I think it makes sense. If `PieContainer` or `Aligner` are going to be used in multiple components then it sounds like a good abstraction. It's essentially the same as having a separate CSS file or JS file of inline styles. The main difference is that the styled components come with the HTML tag as well.
