### ISSUE TITLE
Eventbrites Future = PWA + MoreMicroServices + Server-less ?? Y/N/M? 

### ISSUE THREAD

**Issue by st-fresh** [benmvp/ama#3]
### I learned quite a bit at the recent Reactathon Hiring Mixer....
**Unfortunately I didn’t reach you with a question so this place can suffice...** 
*Nice two-wheeler btw caught you in the elevator on the way out of Lobby 2.*
>   So I’m not sure how much of Eventbrite utilizes Microservices, but do you think that such services (or features) of the Eventbrite app are going to be split between offline and online so then a Progressive Architecture will be a part of Eventbrites app? And if so do you see a Server-less lambda supporting this type of architecture? 

## I’m not sure I’m asking this question perfectly right so...
**I’m going to ask it differently in less words: **
*Since Eventbrite is just buying-and-paying for a thing online, just like FlipCart is.. then shouldn’t the app lean towards PWA(?), and if you are leaning towards it- do you believe more micro-services and a Sever-less architecture support a PWA structure that you would adopt?*

# This question is kind of interesting in that I’m asking you about your company work... 
**So if you need to anonymize your answer and refer to “any software utilizing a thing to be purchased online as it’s core feature” then these are the softwares I’m speaking of..  **
* While I could understand Netflix only booting up a server for my Netflix watching when I’m watching Netflix..
*   I’m not sure your apps selling of tickets/things online needs to utilize this same architecture to provide better end-user experience(?)- but this is an answer I believe you know.
*  (I have worked primarily with Educational platforms that use more messaging, doc-sharing, simple math-biz-logic, and filtering features so e-commerce is not an app architecture I’m as familiar with.. did work with Stripe API once, and Shopify). 

>   I appreciate your answer(s).. I know I've asked multiple questions.. sorry I'm the long-winded type..

**Comment by benmvp** [comment]
Hey @st-fresh! Thanks for the question(s)! 😉 Sorry for the delay in getting back to you when. Been putting the final touches on my React Conf talk on React + ES.next.

Anyway, my scooter is a [Swagger](https://www.amazon.com/SWAGTRON-Swagger-Electric-Ultra-Lightweight-Fold-n-Carry/dp/B01LDPT33A/) scooter by Swagtron. Terrible name, but lots of fun to ride. Makes getting to and from Bart much easier.

We have been talking about making Eventbrite's website a collection of PWAs. It's currently a collection of SPAs so we'd just need to add service workers to make it progressive. What's up in the air is which pages to convert. The marketing/landing/home/search pages are obvious choices. But should the event page be offline? If you're trying to buy tickets for an event w/ limited tickets like a React Conf we need to make sure that you don't have access to inventory that doesn't exist. So you need to be online.

But the ability to get access to your tickets as an attendee or even make changes to your event as an organizer that'll later be reflected as you get back online are all things we'd like to add.

I'm not all that familiar with serverless architecture (yet), so I can't speak much to that. There hasn't been much discussion about it. So not sure if it doesn't make sense for us or just something we haven't explored.

Hopefully that answers your question(s)!

**Comment by st-fresh** [comment]
Thanks @benmvp - your answers really gave me some perspective on PWA's

**Comment by benmvp** [comment]
You're very welcome!
